// Originally generated by the Supabase scaffolding, and no longer regenerable
// without losing the key handling below. Edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://oyewjuvpnavwhmdiqfve.supabase.co";

/**
 * The browser's key. Safe to ship: it identifies the project, and Row Level
 * Security is what actually decides who may read what. Supabase's own console
 * says publishable keys can be shared publicly.
 *
 * THIS USED TO BE THE LEGACY `anon` KEY, hardcoded, with the env var that
 * .env already defined being ignored. That mattered more than it looks:
 * revoking the leaked legacy service_role key means disabling ALL legacy JWT
 * API keys, and the anon key is one of them - so the only thing standing
 * between this app and a total outage at that moment was a string literal
 * nobody could change without a code deploy.
 *
 * Now it reads the environment first and falls back to the new publishable
 * key, so the value can be rotated from Vercel without touching code.
 */
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "sb_publishable_4TbwrzGn3fCGZy8MstTPew_PCr9RD92";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});